title: R. Block Nation – Regulated Funding Portal
description: BD & Compliance Packet for Reg CF Evaluation
theme: minima
markdown: kramdown
baseurl: "/RBlock-BD-Packet" # This must match the repository name

